const assets = [
  {code:'AST-FSD01-R01-AC',name:'Split Air Conditioner 1.5 Ton',icon:'❄',campus:'Faisalabad Campus',room:'Classroom 01',category:'Electrical & HVAC',qty:2,available:2,cost:185000,condition:'good',status:'assigned',verified:'02 Aug 2026',progress:100},
  {code:'AST-FSD01-R01-WHITEBOARD',name:'Classroom Whiteboard 4×8 ft',icon:'▭',campus:'Faisalabad Campus',room:'Classroom 01',category:'Teaching Aids',qty:2,available:2,cost:28000,condition:'good',status:'assigned',verified:'02 Aug 2026',progress:100},
  {code:'AST-FSD01-R01-FAN',name:'Ceiling Fan 56 inch',icon:'✣',campus:'Faisalabad Campus',room:'Classroom 01',category:'Electrical & HVAC',qty:4,available:4,cost:18500,condition:'fair',status:'assigned',verified:'02 Aug 2026',progress:82},
  {code:'AST-FSD01-R01-CHAIR',name:'Student Classroom Chair',icon:'♧',campus:'Faisalabad Campus',room:'Classroom 01',category:'Furniture & Fixtures',qty:50,available:50,cost:6800,condition:'good',status:'assigned',verified:'02 Aug 2026',progress:100},
  {code:'AST-GBLHR-R02-AC',name:'Split Air Conditioner 1.5 Ton',icon:'❄',campus:'Gulberg Campus',room:'Classroom 02',category:'Electrical & HVAC',qty:2,available:2,cost:196100,condition:'good',status:'assigned',verified:'02 Aug 2026',progress:100},
  {code:'AST-GTLHR-R08-PROJECTOR',name:'Multimedia Projector',icon:'◫',campus:'Garden Town Campus',room:'Classroom 08',category:'Teaching Aids',qty:1,available:1,cost:145000,condition:'fair',status:'assigned',verified:'18 Jun 2026',progress:65},
  {code:'AST-MTLHR-GENERATOR',name:'Standby Diesel Generator',icon:'⚡',campus:'Model Town Campus',room:'Utility Area',category:'Generators & Solar',qty:1,available:1,cost:1850000,condition:'maintenance',status:'maintenance',verified:'12 Jul 2026',progress:40},
  {code:'STK-MUL01-TONER',name:'Laser Printer Toner',icon:'▣',campus:'Multan Campus',room:'IT Store',category:'Consumable Stores',qty:28,available:7,cost:18500,condition:'good',status:'in stock',verified:'10 Aug 2026',progress:25},
  {code:'AST-MUL01-R12-CHAIR',name:'Student Classroom Chair',icon:'♧',campus:'Multan Campus',room:'Classroom 12',category:'Furniture & Fixtures',qty:50,available:48,cost:8432,condition:'fair',status:'assigned',verified:'02 Aug 2026',progress:96},
  {code:'AST-FSD01-MICROSCOPE',name:'Binocular Laboratory Microscope',icon:'⌕',campus:'Faisalabad Campus',room:'Biology Lab',category:'Laboratory Equipment',qty:20,available:20,cost:72000,condition:'good',status:'assigned',verified:'05 Aug 2026',progress:100},
  {code:'AST-GBLHR-CCTV',name:'CCTV Camera and NVR System',icon:'◉',campus:'Gulberg Campus',room:'Campus',category:'Security & Surveillance',qty:1,available:1,cost:927500,condition:'good',status:'assigned',verified:'28 Jul 2026',progress:100},
  {code:'STK-GTLHR-CHEMICAL',name:'Laboratory Chemical Reagent Pack',icon:'♨',campus:'Garden Town Campus',room:'Chemistry Lab Store',category:'Consumable Stores',qty:45,available:9,cost:9520,condition:'fair',status:'in stock',verified:'09 Aug 2026',progress:20}
];

const views = {
  ledger:{title:'Ledger Pro',score:'9.6 / 10',summary:'The strongest default for daily inventory work: high information density, sorting, bulk actions and spreadsheet familiarity.',render:renderLedger},
  split:{title:'Split Inspector',score:'9.3 / 10',summary:'Keeps the list visible while opening complete asset details, history and actions—excellent for frequent record review.',render:renderSplit},
  matrix:{title:'Room Matrix',score:'9.5 / 10',summary:'Purpose-built for your classroom model. One row per room instantly exposes missing ACs, boards, fans or chairs.',render:renderMatrix},
  tree:{title:'Location Tree',score:'9.1 / 10',summary:'Navigates inventory the way administrators think: campus → building → floor → room, with contextual totals.',render:renderTree},
  audit:{title:'Audit Command',score:'9.2 / 10',summary:'Surfaces only exceptions, overdue verification, shortages and maintenance—ideal for principals and compliance teams.',render:renderAudit}
};

let currentView='ledger';
const canvas=document.getElementById('designCanvas');
const search=document.getElementById('searchInput');
const branch=document.getElementById('branchFilter');
const money=n=>`₨ ${Number(n).toLocaleString('en-PK')}`;
const filtered=()=>assets.filter(a=>(branch.value==='all'||a.campus===branch.value)&&`${a.code} ${a.name} ${a.campus} ${a.room} ${a.category}`.toLowerCase().includes(search.value.toLowerCase()));
const badge=value=>`<span class="status ${value.replace(' ','-')}">${value}</span>`;
const assetCell=a=>`<div class="asset-cell"><span class="asset-type">${a.icon}</span><span><strong>${a.name}</strong><small>${a.code}</small></span></div>`;

function render(){const view=views[currentView];document.getElementById('viewTitle').textContent=view.title;document.getElementById('viewSummary').textContent=view.summary;document.getElementById('viewScore').textContent=view.score;canvas.innerHTML=view.render(filtered());bindDynamic()}

function renderLedger(data){return `<div class="surface"><div class="surface-head"><div><h2>Asset ledger</h2><p>${data.length} visible records · sorted by last updated</p></div><div class="surface-actions"><button>Bulk update</button><button>Save view</button><button>Columns ☷</button></div></div><div class="table-scroll"><table class="data-table"><thead><tr><th><input class="check" type="checkbox"></th><th>Asset</th><th>Campus / Location</th><th>Available</th><th>Condition</th><th>Unit cost</th><th class="optional-mobile">Verification</th><th>Status</th><th></th></tr></thead><tbody>${data.map(a=>`<tr><td><input class="check" type="checkbox"></td><td>${assetCell(a)}</td><td><div class="stack"><strong>${a.room}</strong><small>${a.campus}</small></div></td><td><div class="stack"><strong>${a.available} / ${a.qty}</strong><div class="progress"><i style="width:${a.progress}%"></i></div></div></td><td>${badge(a.condition)}</td><td><strong>${money(a.cost)}</strong></td><td class="optional-mobile"><div class="stack"><strong>${a.verified}</strong><small>Next: Aug 2027</small></div></td><td>${badge(a.status)}</td><td><button class="row-actions">•••</button></td></tr>`).join('')}</tbody></table></div>${tableFooter(data.length)}</div>`}

function renderSplit(data){const active=data[0]||assets[0];return `<div class="surface split-layout"><div class="master-list"><div class="master-header"><span>Asset</span><span>Location</span><span>Qty</span><span>Condition</span></div>${data.map((a,i)=>`<button class="master-row ${i===0?'active':''}" data-code="${a.code}"><span class="master-asset"><span>${a.icon}</span><span><strong>${a.name}</strong><small>${a.code}</small></span></span><span>${a.room}</span><span>${a.available}/${a.qty}</span><span>${badge(a.condition)}</span></button>`).join('')}</div><aside class="inspector" id="inspector">${inspector(active)}</aside></div>`}
function inspector(a){return `<div class="inspector-title"><span class="big-icon">${a.icon}</span>${badge(a.status)}</div><h2>${a.name}</h2><div class="asset-code">${a.code}</div><div class="inspector-stats"><div><small>Available</small><strong>${a.available} / ${a.qty}</strong></div><div><small>Unit cost</small><strong>${money(a.cost)}</strong></div><div><small>Condition</small><strong>${a.condition}</strong></div></div><div class="detail-list"><div><span>Campus</span><b>${a.campus}</b></div><div><span>Location</span><b>${a.room}</b></div><div><span>Category</span><b>${a.category}</b></div><div><span>Last verified</span><b>${a.verified}</b></div><div><span>Custodian</span><b>Academic Coordinator</b></div></div><div class="timeline"><h3>Activity ledger</h3><div class="timeline-item"><b>Physical verification completed</b><small>${a.verified} · Subhan Ali</small></div><div class="timeline-item"><b>Assigned to ${a.room}</b><small>15 Apr 2025 · Principal</small></div><div class="timeline-item"><b>Opening balance recorded</b><small>12 Jan 2024 · Accounts Office</small></div></div><button class="button primary" style="width:100%">Record transaction</button></aside>`}

function renderMatrix(){const rooms=Array.from({length:30},(_,i)=>({no:i+1,issue:i===7?'fan':i===18?'chair':i===25?'ac':null}));return `<div class="surface"><div class="surface-head"><div><h2>Faisalabad Campus · Classroom asset matrix</h2><p>30 rooms · expected standard: 2 AC, 2 boards, 4 fans, 50 chairs</p></div><div class="matrix-legend"><span><i class="dot"></i>Complete</span><span><i class="dot warn"></i>Variance</span></div></div><div class="matrix-wrap"><table class="room-matrix"><thead><tr><th>Room</th><th>AC</th><th>Whiteboards</th><th>Ceiling fans</th><th>Chairs</th><th>Total units</th><th>Book value</th><th>Verified</th><th>Health</th></tr></thead><tbody>${rooms.map(r=>{const ac=r.issue==='ac'?1:2,fan=r.issue==='fan'?3:4,chair=r.issue==='chair'?48:50,total=ac+2+fan+chair,problem=!!r.issue;return `<tr><td><div class="room-name"><span>▦</span><span><strong>Classroom ${String(r.no).padStart(2,'0')}</strong><small>Academic Block · Floor ${Math.ceil(r.no/10)}</small></span></div></td><td><span class="quantity-pill ${r.issue==='ac'?'warn':''}"><i></i>${ac}/2</span></td><td><span class="quantity-pill"><i></i>2/2</span></td><td><span class="quantity-pill ${r.issue==='fan'?'warn':''}"><i></i>${fan}/4</span></td><td><span class="quantity-pill ${r.issue==='chair'?'warn':''}"><i></i>${chair}/50</span></td><td><b>${total}/58</b></td><td>${money(ac*185000+56000+fan*18500+chair*6800)}</td><td>02 Aug 2026</td><td>${problem?badge('fair'):badge('good')}</td></tr>`}).join('')}</tbody></table></div>${tableFooter(30)}</div>`}

function renderTree(data){return `<div class="surface tree-shell"><aside class="location-tree"><input class="tree-search" placeholder="Find a location…"><div class="tree-node"><span>⌄</span><strong>All campuses</strong><b>730</b></div><div class="tree-children"><div><div class="tree-node active"><span>⌄</span>Faisalabad Campus<b>146</b></div><div class="tree-children"><div><div class="tree-node"><span>⌄</span>Academic Block<b>120</b></div><div class="tree-children"><div class="tree-node active"><span>▦</span>Floor 1<b>580</b></div><div class="tree-node"><span>▦</span>Floor 2<b>580</b></div><div class="tree-node"><span>▦</span>Floor 3<b>580</b></div></div></div><div class="tree-node"><span>▣</span>Science Block<b>32</b></div><div class="tree-node"><span>▣</span>Admin Block<b>18</b></div></div></div><div class="tree-node"><span>›</span>Gulberg Campus<b>146</b></div><div class="tree-node"><span>›</span>Garden Town Campus<b>146</b></div><div class="tree-node"><span>›</span>Model Town Campus<b>146</b></div><div class="tree-node"><span>›</span>Multan Campus<b>146</b></div></div></aside><section class="tree-content"><div class="location-hero"><div><p>FAISALABAD / ACADEMIC BLOCK</p><h2>Floor 1 · Classrooms 01–10</h2><p>Last physical verification: 02 August 2026</p></div><div class="location-total"><strong>580</strong><small>physical units</small></div></div><div class="tree-assets"><div><small>Air conditioners</small><strong>20</strong></div><div><small>Whiteboards</small><strong>20</strong></div><div><small>Ceiling fans</small><strong>39 <em style="color:#b45309;font-size:7px">−1</em></strong></div><div><small>Student chairs</small><strong>498 <em style="color:#b45309;font-size:7px">−2</em></strong></div></div><div class="surface" style="box-shadow:none"><div class="surface-head"><div><h2>Assets in this location</h2><p>Filtered from hierarchy selection</p></div><div class="surface-actions"><button>Verify floor</button></div></div><div class="table-scroll"><table class="data-table" style="min-width:650px"><thead><tr><th>Asset</th><th>Room</th><th>Quantity</th><th>Condition</th><th>Status</th></tr></thead><tbody>${data.slice(0,6).map(a=>`<tr><td>${assetCell(a)}</td><td>${a.room}</td><td>${a.available}/${a.qty}</td><td>${badge(a.condition)}</td><td>${badge(a.status)}</td></tr>`).join('')}</tbody></table></div></div></section></div>`}

function renderAudit(){const issues=[assets[6],assets[11],assets[5],assets[8],assets[2]];return `<div class="audit-shell"><section class="audit-board"><div class="audit-banner"><span>!</span><div><h2>18 records need attention</h2><p>Prioritized by financial risk, operational impact and verification age.</p></div></div>${issues.map((a,i)=>`<div class="exception-row"><i class="severity ${i<2?'red':''}"></i><div><strong>${a.name}</strong><small>${a.code}</small></div><span><b>${a.room}</b><small>${a.campus}</small></span><span>${i<2?'High':'Medium'} risk</span><span>${i===0?'Maintenance':i===1?'Low stock':'Verify'}</span><button>Resolve →</button></div>`).join('')}<div class="table-footer"><span>Showing highest-priority exceptions</span><a style="color:#2563eb;font-weight:700">View all 18 →</a></div></section><aside class="audit-side"><h3>Inventory assurance</h3><div class="ring"><span><strong>94%</strong><small>verified</small></span></div><div><div class="audit-stat"><span>Rooms complete</span><b>142 / 150</b></div><div class="audit-stat"><span>Verification overdue</span><b style="color:#b45309">7</b></div><div class="audit-stat"><span>Under maintenance</span><b style="color:#b91c1c">3</b></div><div class="audit-stat"><span>Low-stock lines</span><b style="color:#b45309">8</b></div><div class="audit-stat"><span>Unresolved value</span><b>₨ 2.4M</b></div><button class="audit-cta">Start guided audit</button></div></aside></div>`}

function tableFooter(count){return `<div class="table-footer"><span>Showing 1–${Math.min(count,10)} of ${count} records</span><div class="pagination"><button>‹</button><button class="active">1</button><button>2</button><button>3</button><button>›</button></div></div>`}

function bindDynamic(){document.querySelectorAll('.master-row').forEach(row=>row.addEventListener('click',()=>{document.querySelectorAll('.master-row').forEach(r=>r.classList.remove('active'));row.classList.add('active');const item=assets.find(a=>a.code===row.dataset.code);document.getElementById('inspector').innerHTML=inspector(item)}))}
document.querySelectorAll('.proposal').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.proposal').forEach(b=>b.classList.remove('active'));button.classList.add('active');currentView=button.dataset.view;render()}));
search.addEventListener('input',render);branch.addEventListener('change',render);render();
