const I = (name) => `<span class="material-symbols-rounded">${name}</span>`;
const status = () => `<div class="status-bar"><span>9:41</span><span class="status-icons">${I('signal_cellular_alt')}${I('wifi')}${I('battery_full')}</span></div>`;
const appbar = (title, {back=false, brand=false, actions=true}={}) => `<div class="appbar">${back?`<button class="appbar-action">${I('arrow_back')}</button>`:''}<div class="appbar-title">${brand?`<span class="appbar-logo">${I('school')}</span>`:''}${title}</div>${actions?`<button class="appbar-action">${I('person')}</button><button class="appbar-action">${I('notifications')}<i class="badge">3</i></button>`:''}</div>`;
const nav = (items, active=0) => `<nav class="bottom-nav">${items.map((x,i)=>`<button class="${i===active?'active':''}">${I(x[0])}<span>${x[1]}</span></button>`).join('')}</nav>`;
const studentNav = (active=0) => nav([['home','Home'],['calendar_today','Timetable'],['bar_chart','Results'],['account_balance_wallet','Fees'],['notifications','Notifications']],active);
const teacherNav = (active=0) => nav([['home','Home'],['how_to_reg','Attendance'],['grading','Marks'],['assignment','Assignments'],['notifications','Notifications']],active);
const principalNav = (active=0) => nav([['home','Home'],['analytics','Attendance'],['bar_chart','Results'],['notifications','Notifications']],active);
const adminNav = (active=0) => nav([['dashboard','Home'],['group','Users'],['qr_code_2','QR Code'],['settings','Settings']],active);
const row = (icon,title,sub,tail='',color='var(--primary)') => `<div class="list-row"><div class="list-icon" style="--row-color:${color}">${I(icon)}</div><div class="list-copy"><div class="list-title">${title}</div><div class="list-sub">${sub}</div></div>${tail?`<div class="list-tail">${tail}</div>`:''}</div>`;
const section = (title, body, action='See all') => `<div class="section-head"><h3>${title}</h3>${action?`<button>${action}</button>`:''}</div>${body}`;
const stat = (icon,label,value,color='var(--primary)') => `<div class="stat-card" style="--stat-color:${color}"><div class="stat-top"><span>${label}</span><span class="stat-icon">${I(icon)}</span></div><div class="stat-value">${value}</div></div>`;
const shell = (body, bottom='', klass='') => `<div class="app-screen ${klass}">${status()}${body}${bottom}</div>`;
const scroll = (body, withNav=true) => `<div class="screen-scroll"><div class="content ${withNav?'with-nav':''}">${body}</div></div>`;
const card = (rows) => `<div class="m-card">${rows}</div>`;

const screens = [
  {id:'scan',group:'Onboarding',role:'Onboarding',label:'Scan school QR',icon:'qr_code_scanner',pattern:'Immersive scanner',copy:'Dark camera surface, minimal chrome, centered 230px scan target, and a secondary upload action.',measures:[['Scan target','230 × 230'],['Horizontal inset','30 px'],['Action radius','12 px']],render:()=>shell(`${appbar('',{back:false,actions:false})}<div class="scanner"><div>${I('qr_code_scanner')}<h2>Scan School QR Code</h2><p>Point your camera at the QR code provided by your school admin</p><div class="scan-frame"><i class="scan-line"></i></div><button class="upload-button">${I('image')} &nbsp; Upload QR</button></div></div>`,'','scan-screen')},
  {id:'confirm',group:'Onboarding',role:'Onboarding',label:'Confirm school',icon:'domain_verification',pattern:'Confirmation card',copy:'A centered organization card confirms identity before saving the school configuration.',measures:[['Page inset','28 px'],['Card radius','24 px'],['Logo radius','22 px']],render:()=>shell(`<div class="confirm-wrap"><div class="school-card"><div class="school-logo">${I('school')}</div><span class="eyebrow">Is this your school?</span><h2>Beaconhouse Academy</h2><p>School Management Platform</p><div class="school-url">school.edustack.pk/beaconhouse</div><button class="primary-button">Yes, this is my school</button><button class="outline-button" style="margin-top:9px">Scan a different QR</button></div></div>`)},
  {id:'login',group:'Authentication',role:'Authentication',label:'Sign in',icon:'login',pattern:'Split hero + form',copy:'Fixed blue gradient hero occupies 46% of the viewport; the white form sheet overlaps with a 32px top radius.',measures:[['Hero height','46%'],['Sheet radius','32 px'],['Button height','52 px']],render:()=>`<div class="app-screen login-screen">${status()}<div class="login-hero"><div class="switch-school">${I('qr_code_scanner')}<span>SWITCH SCHOOL</span></div><div class="login-logo">${I('school')}</div><h2>Beaconhouse Academy</h2><p>Sign in to continue</p></div><div class="login-form"><div class="role-selector"><span>Admin</span><span>Teacher</span><span class="active">Student</span></div><div style="height:16px"></div><div class="field">${I('mail')}<span>Email address</span></div><div class="field">${I('lock')}<span>Password</span>${I('visibility_off')}</div><button class="primary-button">Sign In</button><div class="helper">Secure access powered by EduStack</div></div></div>`},
  {id:'student-dashboard',group:'Student',role:'Student',label:'Dashboard',icon:'home',pattern:'Student dashboard shell',copy:'Floating brand app bar, primary welcome banner, a two-column stats grid, and stacked sections above five-tab navigation.',measures:[['Content gutter','16 px'],['Hero radius','20 px'],['Stats gap','12 px']],render:()=>shell(`${appbar('Beaconhouse Academy',{brand:true})}${scroll(`<div class="hero-card"><div class="hero-copy"><div class="hero-kicker">Welcome,</div><div class="hero-name">Ayesha Khan</div><div class="hero-meta">Grade 8 · Sec A · Roll #14</div></div><div class="avatar">AK</div></div><div class="stat-grid">${stat('check_circle','Attendance','92%','var(--green)')}${stat('grade','Last grade','A','var(--green)')}${stat('account_balance_wallet','Fee due','Rs 8,500','var(--orange)')}${stat('event','Next exam','6d left','var(--blue)')}</div>${section("Today's schedule",card(row('menu_book','Mathematics','08:00–08:45 · Room 12','NOW')+row('science','General Science','09:00–09:45 · Lab 2','Next')))}${section('Next exam',card(row('event','Mathematics — Mid Term','20 August 2026','6d')))}${section('Assignments',card(row('assignment','Algebra worksheet','Mathematics','Due tomorrow','var(--orange)')))}`)}${studentNav(0)}`)},
  {id:'timetable',group:'Student',role:'Student',label:'Timetable',icon:'calendar_today',pattern:'Tabbed schedule',copy:'Seven-day tab bar with vertically stacked period cards and small timing/status labels.',measures:[['Tab height','48 px'],['Card inset','14 px'],['Period badge','R20']],render:()=>shell(`${appbar('Timetable',{actions:false})}<div class="tabs">${['Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<div class="tab ${i===0?'active':''}">${d}</div>`).join('')}</div>${scroll(`${card(row('calculate','Mathematics','08:00–08:45 · Room 12','Period 1')+row('science','General Science','08:45–09:30 · Lab 2','Period 2')+row('translate','English','09:45–10:30 · Room 12','Period 3')+row('public','Pakistan Studies','10:30–11:15 · Room 8','Period 4'))}`,true)}${studentNav(1)}`)},
  {id:'results',group:'Student',role:'Student',label:'Results',icon:'bar_chart',pattern:'Result summary cards',copy:'Exam cards surface overall percentage and grade before a subject breakdown and PDF action.',measures:[['Card radius','12 px'],['Card padding','16 px'],['Status pill','R20']],render:()=>shell(`${appbar('Results',{actions:false})}${scroll(`<div class="filter-row"><span class="filter-chip active">Mid Term 2026</span><span class="filter-chip">Final 2025</span></div><div class="summary-card"><div class="summary-line"><div><span class="eyebrow">Overall result</span><h2 style="margin:5px 0 0;font-size:23px">87.4%</h2></div><div class="donut" data-label="A"></div></div><span class="pill" style="--pill-color:var(--green)">PASSED</span></div>${section('Subject Breakdown',card(row('calculate','Mathematics','86 / 100','A')+row('science','General Science','91 / 100','A+')+row('translate','English','82 / 100','B+')+row('public','Pakistan Studies','88 / 100','A')),'')}<button class="primary-button">${I('download')} &nbsp; Download PDF</button>`)}${studentNav(2)}`)},
  {id:'attendance',group:'Student',role:'Student',label:'My attendance',icon:'fact_check',pattern:'Progress summary',copy:'A compact attendance summary combines an overall donut, status counts, and a dated history list.',measures:[['Page inset','16 px'],['Summary radius','16 px'],['Progress height','5 px']],render:()=>shell(`${appbar('Attendance',{actions:false})}${scroll(`<div class="summary-card"><div class="summary-line"><div><span class="eyebrow">Overall attendance</span><h2 style="margin:5px 0 0;font-size:23px">92%</h2><p style="font-size:9px;color:var(--on-surface-variant)">110 of 120 school days</p></div><div class="donut" data-label="92%"></div></div><div class="progress" style="--pct:92%;--bar:var(--green)"><i></i></div></div><div class="stat-grid">${stat('check','Present','110','var(--green)')}${stat('close','Absent','6','var(--error)')}</div>${section('Recent history',card(row('check_circle','Wednesday, 13 Aug','Present','P','var(--green)')+row('check_circle','Tuesday, 12 Aug','Present','P','var(--green)')+row('schedule','Monday, 11 Aug','Late','L','var(--orange)')),'')}`)}${studentNav(0)}`)},
  {id:'assignments',group:'Student',role:'Student',label:'Assignments',icon:'assignment',pattern:'Tabbed task list',copy:'All/Pending tabs lead into bordered assignment cards with subject and due-status chips.',measures:[['Card radius','12 px'],['Card padding','14 px'],['Chip inset','8 × 2']],render:()=>shell(`${appbar('Assignments',{actions:false})}<div class="tabs"><div class="tab active">All</div><div class="tab">Pending</div></div>${scroll(`${card(row('functions','Algebra worksheet','Mathematics · Due 15 Aug','DUE TOMORROW','var(--orange)')+row('biotech','Plant cell diagram','General Science · Due 18 Aug','4 DAYS')+row('history_edu','Essay: My Country','English · Submitted','DONE','var(--green)'))}`)}${studentNav(0)}`)},
  {id:'fees',group:'Student',role:'Student',label:'Fee challans',icon:'account_balance_wallet',pattern:'Financial status list',copy:'Outstanding total is prioritized, followed by grouped unpaid and paid challan cards with strong status pills.',measures:[['Summary padding','18 px'],['List radius','12 px'],['Status pill','R20']],render:()=>shell(`${appbar('Fee Challans',{actions:false})}${scroll(`<div class="summary-card"><span class="eyebrow">Total outstanding</span><h2 style="margin:7px 0 3px;font-size:23px;color:var(--error)">PKR 8,500</h2><span style="font-size:9px;color:var(--on-surface-variant)">Due 20 August 2026</span></div>${section('Outstanding (1)',card(row('receipt_long','August 2026','# BCH-0826-014','UNPAID','var(--error)')),'')}${section('Paid (2)',card(row('receipt_long','July 2026','# BCH-0726-014','PAID','var(--green)')+row('receipt_long','June 2026','# BCH-0626-014','PAID','var(--green)')),'')}`)}${studentNav(3)}`)},
  {id:'classmates',group:'Student',role:'Student',label:'Class fellows',icon:'groups',pattern:'Roster + performance',copy:'Searchable class roster with a warm topper callout and compact student rows.',measures:[['Search gutter','16 px'],['Topper padding','14 px'],['Avatar radius','50%']],render:()=>shell(`${appbar('Class Fellows',{actions:false})}${scroll(`<div class="field">${I('search')}<span>Search classmates</span></div><div class="notice" style="background:#fff8e1"><span style="font-size:26px">🏆</span><div><b>Class Topper</b><br>Ayesha Khan · 94.6%</div></div>${section('Grade 8 · Section A',card(row('person','Ayesha Khan','Roll #14','94.6%','var(--orange)')+row('person','Hamza Ali','Roll #03','91.2%')+row('person','Sara Ahmed','Roll #19','89.8%')+row('person','Daniyal Shah','Roll #07','86.4%')),'')}`)}${studentNav(0)}`)},
  {id:'notifications',group:'Student',role:'Shared',label:'Notifications',icon:'notifications',pattern:'Notification inbox',copy:'Read state is communicated through tinted icon containers, with a single text action in the app bar.',measures:[['Row inset','12 px'],['Icon radius','10 px'],['Title size','13 px']],render:()=>shell(`${appbar('Notifications',{actions:false})}${scroll(`<div style="display:flex;justify-content:flex-end;margin-bottom:8px"><span style="font-size:9px;color:var(--primary);font-weight:700">Mark all read</span></div>${card(row('assignment','New assignment posted','Mathematics · Algebra worksheet','2m','var(--blue)')+row('campaign','School will remain closed','Public holiday notice','1h','var(--orange)')+row('payments','Fee challan generated','August 2026 challan is ready','Yesterday','var(--green)')+row('grade','Results published','Mid Term 2026 results are available','2d'))}`)}${studentNav(4)}`)},
  {id:'teacher-dashboard',group:'Teacher',role:'Teacher',label:'Dashboard',icon:'space_dashboard',pattern:'Teacher work queue',copy:'The teacher dashboard reuses the primary welcome banner and replaces student stats with operational quick actions.',measures:[['Hero padding','20 px'],['Quick card radius','14 px'],['Section gap','24 px']],render:()=>shell(`${appbar('Beaconhouse Academy',{brand:true})}${scroll(`<div class="hero-card"><div class="hero-copy"><div class="hero-kicker">Good morning,</div><div class="hero-name">Mr. Usman</div><div class="hero-meta">Mathematics Teacher · 4 classes today</div></div><div class="avatar">MU</div></div>${section('Quick actions',`<div class="quick-grid"><div class="quick">${I('how_to_reg')}Attendance</div><div class="quick">${I('grading')}Enter marks</div><div class="quick">${I('add_task')}Assignment</div><div class="quick">${I('groups')}Classes</div></div>`,'')}${section("Today's Classes",card(row('calculate','Grade 8-A · Mathematics','08:00–08:45 · Room 12','NOW')+row('calculate','Grade 9-B · Mathematics','10:30–11:15 · Room 6','10:30')))}${section('Pending Actions',card(row('assignment_late','Grade 8 homework','12 submissions to review','12','var(--orange)')+row('edit_note','Mid Term marks','Grade 9-B incomplete','6','var(--error)')),'')}`)}${teacherNav(0)}`)},
  {id:'select-class',group:'Teacher',role:'Teacher',label:'Select class',icon:'how_to_reg',pattern:'Class selection list',copy:'Assigned classes are presented as tappable list cards before entering the attendance workflow.',measures:[['Page inset','16 px'],['Card radius','14 px'],['List vertical','14 px']],render:()=>shell(`${appbar('Mark Attendance',{actions:false})}${scroll(`<div class="notice">${I('calendar_today')}<div><b>Thursday, 14 August</b><br>Select a class to mark today's attendance.</div></div>${section('My classes',card(row('calculate','Grade 8 · Section A','Mathematics · 28 students',I('chevron_right'))+row('calculate','Grade 9 · Section B','Mathematics · 31 students',I('chevron_right'))+row('calculate','Grade 10 · Section A','Mathematics · 26 students',I('chevron_right'))),'')}`)}${teacherNav(1)}`)},
  {id:'mark-attendance',group:'Teacher',role:'Teacher',label:'Mark attendance',icon:'checklist',pattern:'Bulk attendance form',copy:'Context selectors sit above a roster table with clear present/absent/late choices and a persistent save action.',measures:[['Form inset','16 px'],['Status target','26 px'],['Save height','52 px']],render:()=>shell(`${appbar('Grade 8-A',{back:true,actions:false})}${scroll(`<div class="filter-row"><span class="filter-chip active">Period 1</span><span class="filter-chip">Mathematics</span></div><div class="summary-card"><div class="summary-line"><b style="font-size:12px">28 Students</b><span class="pill" style="--pill-color:var(--green)">25 PRESENT</span></div><div class="progress" style="--pct:89%;--bar:var(--green)"><i></i></div></div>${section('Mark all',`<div class="filter-row"><span class="filter-chip active">Present</span><span class="filter-chip">Absent</span><span class="filter-chip">Late</span></div>`,'')}<div class="m-card">${['Ayesha Khan','Hamza Ali','Sara Ahmed','Daniyal Shah'].map((n,i)=>`<div class="list-row"><div class="avatar" style="width:34px;height:34px;color:var(--primary);background:var(--primary-container);font-size:11px">${n.split(' ').map(x=>x[0]).join('')}</div><div class="list-copy"><div class="list-title">${n}</div><div class="list-sub">Roll #${[14,3,19,7][i]}</div></div><div class="attendance-toggle"><span class="present">P</span><span class="absent">A</span><span>L</span></div></div>`).join('')}</div><button class="primary-button" style="margin-top:14px">Save Attendance</button>`)}${teacherNav(1)}`)},
  {id:'marks',group:'Teacher',role:'Teacher',label:'Enter marks',icon:'grading',pattern:'Data-entry table',copy:'Two selectors gate a compact student marks table; the single full-width action follows Material button defaults.',measures:[['Field radius','12 px'],['Row padding','12 px'],['Button height','52 px']],render:()=>shell(`${appbar('Enter Marks',{actions:false})}${scroll(`<div class="field">${I('event')}<span>Mid Term 2026</span>${I('expand_more')}</div><div class="field">${I('groups')}<span>Grade 8 · Section A</span>${I('expand_more')}</div><button class="primary-button">Load Students</button>${section('Mathematics · 100 marks',`<div class="m-card"><table class="table"><thead><tr><th>Student</th><th>Roll</th><th>Marks</th></tr></thead><tbody><tr><td>Ayesha Khan</td><td>14</td><td><span class="filter-chip">86</span></td></tr><tr><td>Hamza Ali</td><td>03</td><td><span class="filter-chip">79</span></td></tr><tr><td>Sara Ahmed</td><td>19</td><td><span class="filter-chip">91</span></td></tr><tr><td>Daniyal Shah</td><td>07</td><td><span class="filter-chip">74</span></td></tr></tbody></table></div>`,'')}<button class="primary-button">Save Marks</button>`)}${teacherNav(2)}`)},
  {id:'teacher-assignments',group:'Teacher',role:'Teacher',label:'Assignments',icon:'assignment_add',pattern:'Managed content list',copy:'Teacher assignment cards add submission counts, overflow actions, and a prominent extended FAB for creation.',measures:[['Card padding','14 px'],['FAB offset','16 px'],['Chip radius','20 px']],render:()=>shell(`${appbar('Assignments',{actions:false})}${scroll(`${card(row('functions','Algebra worksheet','Grade 8-A · Due 15 Aug','12 / 28')+row('calculate','Quadratic equations','Grade 9-B · Due 20 Aug','4 / 31')+row('geometry','Geometry exercise','Grade 10-A · Due 22 Aug','0 / 26'))}`)}<button class="fab">${I('add')}</button>${teacherNav(3)}`)},
  {id:'principal-dashboard',group:'Leadership',role:'Principal',label:'Principal dashboard',icon:'analytics',pattern:'School KPI overview',copy:'Leadership views emphasize aggregate KPIs, alerts, and school-wide progress while retaining the same shell.',measures:[['KPI grid','2 columns'],['Alert threshold','< 75%'],['Hero radius','20 px']],render:()=>shell(`${appbar('Beaconhouse Academy',{brand:true})}${scroll(`<div class="hero-card"><div class="hero-copy"><div class="hero-kicker">Good morning,</div><div class="hero-name">Dr. Fatima</div><div class="hero-meta">Principal</div></div><div class="avatar">DF</div></div><div class="stat-grid">${stat('groups','Students','1,248')}${stat('school','Teachers','72')}${stat('check_circle','Attendance','89.6%','var(--green)')}${stat('payments','Fees collected','84%','var(--blue)')}</div>${section('School attendance',`<div class="summary-card"><div class="summary-line"><b style="font-size:12px">Today</b><b style="font-size:16px;color:var(--green)">89.6%</b></div><div class="progress" style="--pct:89.6%;--bar:var(--green)"><i></i></div></div>`,'View report')}${section('Low Attendance Alerts',card(row('warning','Bilal Ahmed','Grade 7-B · 68%','68%','var(--error)')+row('warning','Maham Khan','Grade 9-A · 72%','72%','var(--orange)')),'')}`)}${principalNav(0)}`)},
  {id:'attendance-report',group:'Leadership',role:'Principal',label:'Attendance report',icon:'query_stats',pattern:'Filterable report',copy:'Date and branch filters precede a simple class table and low-attendance exception list.',measures:[['Filter inset','14 × 10'],['Table padding','10 px'],['Threshold','75%']],render:()=>shell(`${appbar('Attendance Report',{actions:false})}${scroll(`<div class="filter-row"><span class="filter-chip active">14 Aug 2026</span><span class="filter-chip">All branches</span></div>${section('By Class',`<div class="m-card"><table class="table"><thead><tr><th>Class</th><th>Present</th><th>Absent</th></tr></thead><tbody><tr><td>Grade 6-A</td><td style="color:var(--green)">28</td><td style="color:var(--error)">2</td></tr><tr><td>Grade 7-B</td><td style="color:var(--green)">25</td><td style="color:var(--error)">5</td></tr><tr><td>Grade 8-A</td><td style="color:var(--green)">26</td><td style="color:var(--error)">2</td></tr></tbody></table></div>`,'')}${section('Low Attendance Students (< 75%)',card(row('warning','Bilal Ahmed','Grade 7-B','68%','var(--error)')+row('warning','Maham Khan','Grade 9-A','72%','var(--orange)')),'')}`)}${principalNav(1)}`)},
  {id:'coordinator',group:'Leadership',role:'Coordinator',label:'Coordinator dashboard',icon:'hub',pattern:'Operations dashboard',copy:'A tertiary-color identity banner separates the coordinator role, followed by attendance and schedule actions.',measures:[['Hero role color','Tertiary'],['Action columns','4'],['Card radius','14 px']],render:()=>shell(`${appbar('Beaconhouse Academy',{brand:true})}${scroll(`<div class="hero-card tertiary"><div class="hero-copy"><div class="hero-kicker">Academic Operations</div><div class="hero-name">Ms. Hira</div><div class="hero-meta">Coordinator</div></div><div class="avatar">MH</div></div>${section('Quick Actions',`<div class="quick-grid"><div class="quick">${I('analytics')}Attendance</div><div class="quick">${I('calendar_month')}Timetable</div><div class="quick">${I('event')}Exams</div><div class="quick">${I('campaign')}Notices</div></div>`,'')}${section('School Attendance',`<div class="summary-card"><div class="summary-line"><span>1,118 present out of 1,248</span><b style="font-size:16px;color:var(--green)">89.6%</b></div><div class="progress" style="--pct:89.6%;--bar:var(--green)"><i></i></div></div>`,'')}${section('Upcoming Exams',card(row('event','Mid Term — Grade 8','20 August 2026','6d')+row('event','Mid Term — Grade 9','22 August 2026','8d')),'')}`)}${principalNav(0)}`)},
  {id:'accountant',group:'Operations',role:'Accountant',label:'Accountant dashboard',icon:'payments',pattern:'Fee operations dashboard',copy:'A secondary-colored role banner leads into collection KPIs, operational shortcuts, and an unpaid queue.',measures:[['Hero role color','Secondary'],['Action columns','4'],['Currency','PKR']],render:()=>shell(`${appbar('Beaconhouse Academy',{brand:true})}${scroll(`<div class="hero-card secondary"><div class="hero-copy"><div class="hero-kicker">Fee Management</div><div class="hero-name">Ali Raza</div><div class="hero-meta">Accountant</div></div><div class="avatar">AR</div></div><div class="stat-grid">${stat('payments','Collected','PKR 2.4m','var(--green)')}${stat('pending_actions','Outstanding','PKR 460k','var(--error)')}${stat('receipt_long','Paid challans','986')}${stat('warning','Overdue','34','var(--orange)')}</div>${section('Quick Actions',`<div class="quick-grid"><div class="quick">${I('add_card')}Challan</div><div class="quick">${I('receipt')}Payments</div><div class="quick">${I('summarize')}Reports</div><div class="quick">${I('download')}Export</div></div>`,'')}${section('Recent Unpaid',card(row('receipt_long','August 2026 · Ayesha Khan','# BCH-0826-014','PKR 8,500','var(--error)')+row('receipt_long','August 2026 · Hamza Ali','# BCH-0826-003','OVERDUE','var(--error)')))}`)}${nav([['home','Home'],['receipt_long','Challans'],['summarize','Reports'],['notifications','Notifications']],0)}`)},
  {id:'admin',group:'Administration',role:'Admin',label:'Admin dashboard',icon:'admin_panel_settings',pattern:'Administration overview',copy:'Admin screens use a dark neutral hero, role-level KPI cards, and direct links into users, branches, and QR setup.',measures:[['Hero palette','Dark neutral'],['Quick columns','4'],['Shell tabs','4']],render:()=>shell(`${appbar('EduStack Admin',{brand:true})}${scroll(`<div class="hero-card admin"><div class="hero-copy"><div class="hero-kicker">Administration Panel</div><div class="hero-name">Super Admin</div><div class="hero-meta">All systems operational</div></div><div class="avatar">SA</div></div><div class="stat-grid">${stat('domain','Organizations','12')}${stat('account_tree','Branches','34')}${stat('groups','Users','8,420')}${stat('school','Students','6,988')}</div>${section('Quick Actions',`<div class="quick-grid"><div class="quick">${I('person_add')}Add user</div><div class="quick">${I('qr_code_2')}School QR</div><div class="quick">${I('add_business')}Branch</div><div class="quick">${I('settings')}Settings</div></div>`,'')}${section('Organizations',card(row('domain','Beaconhouse Academy','/beaconhouse','Active','var(--green)')+row('domain','City Grammar School','/city-grammar','Active','var(--green)')),'')}`)}${adminNav(0)}`)},
  {id:'users',group:'Administration',role:'Admin',label:'User management',icon:'manage_accounts',pattern:'Role-tabbed directory',copy:'Role tabs and a search control feed a compact user directory with status chips and row actions.',measures:[['Tab count','5 roles'],['Avatar','40 px'],['Status radius','8 px']],render:()=>shell(`${appbar('Users',{actions:false})}<div class="tabs">${['Admin','Teacher','Student','Principal'].map((d,i)=>`<div class="tab ${i===2?'active':''}">${d}</div>`).join('')}</div>${scroll(`<div class="field">${I('search')}<span>Search students</span>${I('filter_list')}</div>${card(row('person','Ayesha Khan','ayesha@school.pk','ACTIVE','var(--green)')+row('person','Hamza Ali','hamza@school.pk','ACTIVE','var(--green)')+row('person','Sara Ahmed','sara@school.pk','INACTIVE','var(--error)'))}`)}${adminNav(1)}`)},
  {id:'qr',group:'Administration',role:'Admin',label:'School QR code',icon:'qr_code_2',pattern:'QR provisioning',copy:'A simple instructional card frames the generated organization QR, with one strong share/print action.',measures:[['Page inset','24 px'],['QR padding','16 px'],['QR card radius','16 px']],render:()=>shell(`${appbar('School QR Code',{actions:false})}${scroll(`<div class="notice">${I('info')}<div><b>How it works</b><br>Staff and students scan this code once to connect their app to your school.</div></div><div class="school-card" style="margin-top:18px;padding:20px"><div style="width:190px;height:190px;margin:auto;display:grid;place-items:center;border:12px solid white;border-radius:16px;background:repeating-conic-gradient(#17212c 0 25%,white 0 50%) 50%/22px 22px;box-shadow:0 4px 14px rgba(0,0,0,.1)"><div class="school-logo" style="width:54px;height:54px;margin:0;border:5px solid white">${I('school')}</div></div><h2 style="margin-top:17px">Beaconhouse Academy</h2><p>/beaconhouse</p></div><button class="primary-button" style="margin-top:14px">${I('share')} &nbsp; Share / Print</button>`)}${adminNav(2)}`)},
  {id:'profile',group:'Shared',role:'Shared',label:'Profile',icon:'person',pattern:'Identity + account',copy:'A large brand-color profile header sits above read-only details and account-level actions.',measures:[['Profile avatar','82 px'],['Header inset','20 px'],['Action radius','12 px']],render:()=>shell(`${appbar('Profile',{back:true,actions:false})}<div class="screen-scroll"><div class="profile-hero"><div class="avatar">AK</div><h2>Ayesha Khan</h2><p>Student · Grade 8-A</p></div><div class="content"><div class="settings-section"><p class="settings-label">PERSONAL DETAILS</p><div class="settings-row">${I('mail')}<div>Email<small>ayesha@school.pk</small></div></div><div class="settings-row">${I('badge')}<div>Roll number<small>14</small></div></div><div class="settings-row">${I('school')}<div>School<small>Beaconhouse Academy</small></div></div></div><div class="settings-section"><div class="settings-row">${I('lock_reset')}<div>Change Password</div>${I('chevron_right')}</div><div class="settings-row" style="color:var(--error)">${I('logout')}<div>Sign Out</div></div></div></div></div>`)},
  {id:'settings',group:'Shared',role:'Shared',label:'Settings',icon:'settings',pattern:'Grouped preferences',copy:'Preferences are grouped into plain Material list sections for appearance, language, app info, and account.',measures:[['Page inset','16 px'],['Group gap','18 px'],['Row padding','12 px']],render:()=>shell(`${appbar('Settings',{back:true,actions:false})}${scroll(`<div class="settings-section"><p class="settings-label">APPEARANCE</p><div class="settings-row">${I('brightness_auto')}<div>Theme<small>System default</small></div>${I('chevron_right')}</div></div><div class="settings-section"><p class="settings-label">LANGUAGE</p><div class="settings-row">${I('language')}<div>English<small>App language</small></div><span class="pill">EN</span></div><div class="settings-row">${I('translate')}<div>اردو<small>Urdu</small></div><span>UR</span></div></div><div class="settings-section"><p class="settings-label">ABOUT</p><div class="settings-row">${I('info')}<div>App Version</div><span>1.0.0</span></div><div class="settings-row">${I('school')}<div>EduStack<small>School Management Platform</small></div></div></div><div class="settings-section"><div class="settings-row" style="color:var(--error)">${I('logout')}<div>Sign Out</div></div></div>`,false)}`)},
  {id:'offline',group:'Shared',role:'Shared',label:'No internet',icon:'wifi_off',pattern:'Connection error state',copy:'A single centered status illustration, direct explanation, and full-width retry action.',measures:[['Icon tile','92 px'],['Tile radius','30 px'],['Button height','52 px']],render:()=>shell(`<div class="offline"><div><div class="offline-icon">${I('wifi_off')}</div><h2>No Internet</h2><p>Check your connection and try again.</p><button class="primary-button" style="min-width:220px">Retry</button></div></div>`)},
];

const navRoot = document.querySelector('#screen-nav');
const device = document.querySelector('#device-screen');
const search = document.querySelector('#screen-search');
const tokenPanel = document.querySelector('#token-panel');
let current = 'student-dashboard';

function buildNav(filter='') {
  navRoot.innerHTML = '';
  const found = screens.filter(s => `${s.group} ${s.label}`.toLowerCase().includes(filter.toLowerCase()));
  [...new Set(found.map(s=>s.group))].forEach(group => {
    const wrap = document.createElement('div'); wrap.className='nav-group';
    wrap.innerHTML=`<div class="nav-group-title">${group}</div>` + found.filter(s=>s.group===group).map(s=>`<button class="nav-item ${s.id===current?'active':''}" data-id="${s.id}">${I(s.icon)}<span>${s.label}</span></button>`).join('');
    navRoot.appendChild(wrap);
  });
  document.querySelector('#screen-count').textContent=`${found.length} of ${screens.length} screens`;
}

function render(id) {
  const screen = screens.find(s=>s.id===id) || screens[0]; current=screen.id;
  device.innerHTML=screen.render();
  document.querySelector('#route-role').textContent=screen.role;
  document.querySelector('#route-path').textContent=screen.label;
  document.querySelector('#screen-title').textContent=screen.label;
  document.querySelector('#pattern-title').textContent=screen.pattern;
  document.querySelector('#pattern-copy').textContent=screen.copy;
  document.querySelector('#measure-list').innerHTML=screen.measures.map(m=>`<div class="measure"><span>${m[0]}</span><b>${m[1]}</b></div>`).join('');
  buildNav(search.value);
}

navRoot.addEventListener('click',e=>{ const b=e.target.closest('[data-id]'); if(b) render(b.dataset.id); });
search.addEventListener('input',()=>buildNav(search.value));
document.querySelector('#tokens-toggle').addEventListener('click',()=>tokenPanel.classList.add('open'));
document.querySelector('#tokens-close').addEventListener('click',()=>tokenPanel.classList.remove('open'));
document.querySelector('#theme-toggle').addEventListener('click',e=>{ device.classList.toggle('dark'); e.currentTarget.querySelector('span').textContent=device.classList.contains('dark')?'light_mode':'dark_mode'; });
document.querySelector('#seed-color').addEventListener('input',e=>{
  const hex=e.target.value; const n=parseInt(hex.slice(1),16); const rgb=[n>>16,(n>>8)&255,n&255];
  document.documentElement.style.setProperty('--primary',hex);
  document.documentElement.style.setProperty('--primary-rgb',rgb.join(', '));
  document.documentElement.style.setProperty('--primary-container',`color-mix(in srgb, ${hex} 18%, #ffffff)`);
  document.querySelector('#primary-value').textContent=hex.toUpperCase();
});

buildNav(); render(current);
